#define NUM_SMS 132
#define MAX_COPY_SMS 128
// #define NUM_SMS 188
// #define MAX_COPY_SMS 188


#define TILE_M 64
#define TILE_N 8
#define TILE_K 256
#define BUFFER_SLOTS 3

#define TILE_M_MULTICAST 64
#define TILE_N_MULTICAST 256
#define TILE_K_MULTICAST 64
#define BUFFER_SLOTS_MULTICAST 3
#define BUFFER_SLOTS_B_MULTICAST 3

#define CHUNK_SIZE_A (TILE_M_MULTICAST * TILE_K_MULTICAST)
#define CHUNK_SIZE_B (TILE_N_MULTICAST * TILE_K_MULTICAST)
#define CHUNK_SIZE_C (TILE_M_MULTICAST * TILE_N_MULTICAST)

#ifndef RECORD_NUM_CHUNKS
#define RECORD_NUM_CHUNKS 0
#endif

#define NUM_PRODUCER_THREADS 32
#define NUM_CONSUMER_THREADS 128

#define CLUSTER_SIZE 2